MODEL: #MODEL field
    framework: "RecognizerGCN" #Mandatory, indicate the type of network, associate to the 'paddlevideo/modeling/framework/'.
    backbone: #Mandatory, indicate the type of backbone, associate to the 'paddlevideo/modeling/backbones/' .
        name: "CTRGCN" #Mandatory, The name of backbone.
        in_channels: 4
    head:
        name: "CTRGCNHead" #Mandatory, indicate the type of head, associate to the 'paddlevideo/modeling/heads'
        num_classes: 30 #Optional, the number of classes to be classified.
        ls_eps: 0.1

DATASET: #DATASET field
    batch_size: 16  #Mandatory, bacth size
    num_workers: 2  #Mandatory, the number of subprocess on each GPU.
    test_batch_size: 1
    test_num_workers: 0
    train:
        format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "../dataset/train/JMj_fold0.npy" #Mandatory, train data index file path
        label_path: "../dataset/train/fold0_label.npy"
    valid:
        format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "../dataset/valid/JMj_fold0.npy" #Mandatory, train data index file path
        label_path: "../dataset/valid/fold0_label.npy"
    test:
        format: "SkeletonDataset" #Mandatory, indicate the type of dataset, associate to the 'paddlevidel/loader/dateset'
        file_path: "../dataset/test/JMj.npy" #Mandatory, valid data index file path
        test_mode: True

PIPELINE: #PIPELINE field
    train: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        sample:
            name: "UniformSampleFrames"
            window_size: 350
        transform: #Mandotary, image transfrom operator
            - SkeletonNorm_JMj:
    valid: #Mandotary, indicate the pipeline to deal with the training data, associate to the 'paddlevideo/loader/pipelines/'
        sample:
            name: "UniformSampleFrames"
            window_size: 350
            test_mode: True
        transform: #Mandotary, image transfrom operator
            - SkeletonNorm_JMj:
    test: #Mandatory, indicate the pipeline to deal with the validing data. associate to the 'paddlevideo/loader/pipelines/'
        sample:
            name: "UniformSampleFrames"
            window_size: 350
            test_mode: True
        transform: #Mandotary, image transfrom operator
            - SkeletonNorm_JMj:

OPTIMIZER: #OPTIMIZER field
 name: 'Momentum'
 momentum: 0.9
 learning_rate:
   iter_step: False
   name: 'CustomWarmupCosineDecay'
   max_epoch: 90
   warmup_epochs: 10
   warmup_start_lr: 0.01
   cosine_base_lr: 0.1
 weight_decay:
   name: 'L2'
   value: 4e-4

METRIC:
    name: 'SkeletonMetric'
    out_file: 'submission.csv'

INFERENCE:
    name: 'STGCN_Inference_helper'
    num_channels: 5
    window_size: 350
    vertex_nums: 25
    person_nums: 1

model_name: "CTRGCN_JMj_fold0"
save_interval: 10
val_interval: 1
log_interval: 20 #Optional, the interal of logger, default:10
epochs: 90 #Mandatory, total epoch
